### ISSUE TITLE
requirement failed 

### ISSUE THREAD

**Issue by ranvijayj** [snowplow/kinesis-s3#114]
`[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at com.snowplowanalytics.snowplow.storage.kinesis.s3.sinks.KinesisSink.<init>(KinesisSink.scala:72)
	at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$.delayedEndpoint$com$snowplowanalytics$snowplow$storage$kinesis$s3$SinkApp$1(SinkApp.scala:90)
	at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$delayedInit$body.apply(SinkApp.scala:45)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$.main(SinkApp.scala:45)
	at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp.main(SinkApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 4 s, completed Aug 14, 2017 12:36:20 PM`

**Comment by ranvijayj** [comment]
`/kinesis-s3$ ../sbt/bin/sbt "run --config config"`

**Comment by ranvijayj** [comment]
@aldemirenes Can you help here?

**Comment by BenFradet** [comment]
It's the same issue as before the stream doesn't exist.

**Comment by alexanderdean** [comment]
Please direct any support questions to our forums: https://discourse.snowplowanalytics.com/
