### ISSUE TITLE
Update documentation to make dependencies on LZO clearer

### ISSUE THREAD

**Issue by fubarbaz** [snowplow/kinesis-s3#72]
When I run the released jar, I get the following output. So, it appears there is a JVM misconfiguration and/or missing dependencies. Can you please fix this, such that either the jar is really self-sufficient or that there is some start script which locates the right resources and passes them to the `java` program?     

```
Dec 08, 2016 11:03:38 AM com.hadoop.compression.lzo.GPLNativeCodeLoader unpackBinaries
SEVERE: could not unpack the binaries
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at com.hadoop.compression.lzo.GPLNativeCodeLoader.unpackBinaries(GPLNativeCodeLoader.java:115)
        at com.hadoop.compression.lzo.GPLNativeCodeLoader.<clinit>(GPLNativeCodeLoader.java:48)
        at com.hadoop.compression.lzo.LzoCodec.<clinit>(LzoCodec.java:71)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.serializers.LzoSerializer$.<init>(LzoSerializer.scala:66)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.serializers.LzoSerializer$.<clinit>(LzoSerializer.scala)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$delayedInit$body.apply(SinkApp.scala:108)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$.main(SinkApp.scala:48)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp.main(SinkApp.scala)

Dec 08, 2016 11:03:38 AM com.hadoop.compression.lzo.GPLNativeCodeLoader <clinit>
SEVERE: Could not load native gpl library
java.lang.UnsatisfiedLinkError: no gplcompression in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at com.hadoop.compression.lzo.GPLNativeCodeLoader.<clinit>(GPLNativeCodeLoader.java:54)
        at com.hadoop.compression.lzo.LzoCodec.<clinit>(LzoCodec.java:71)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.serializers.LzoSerializer$.<init>(LzoSerializer.scala:66)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.serializers.LzoSerializer$.<clinit>(LzoSerializer.scala)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$delayedInit$body.apply(SinkApp.scala:108)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.App$$anonfun$main$1.apply(App.scala:71)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
        at scala.App$class.main(App.scala:71)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp$.main(SinkApp.scala:48)
        at com.snowplowanalytics.snowplow.storage.kinesis.s3.SinkApp.main(SinkApp.scala)

Dec 08, 2016 11:03:38 AM com.hadoop.compression.lzo.LzoCodec <clinit>
SEVERE: Cannot load native-lzo without native-hadoop
```

**Comment by jbeemster** [comment]
Hi @fubarbaz could you please share how exactly you are running it?  We have the latest running in production without any of the above issues.

**Comment by fubarbaz** [comment]
You are running it on Ubuntu; I am running it in a minimal docker container based on busybox. That's the main difference. I suppose one solution would be to say that only Ubuntu as a deployment platform is supported, but that seems rather limited.

**Comment by alexanderdean** [comment]
Hi @fubarbaz - it sounds like your Docker container is too minimal. If you look at the Vagrant deployment for a local development environment for this project:

https://github.com/snowplow/kinesis-s3/blob/master/vagrant/up.playbooks#L5

This is the Ansible playbook used:

https://github.com/snowplow/ansible-playbooks/blob/master/roles/lzo/tasks/main.yml

If you add those to your Docker container you should be good to go!

**Comment by fubarbaz** [comment]
@jbeemster 
Where do you install the native component for the hadoop-lzo library? I.e., https://github.com/twitter/hadoop-lzo/tree/master/src/main/native. AFAICT, the hadoop-lzo jar part works fine, it's just resolving the native components which doesn't work, because they aren't actually installed in the first place. The native parts of the hadoop-lzo dependency  (i.e. libgplcompression.so on Linux) are not installed by anything, AFAIK *unless* you build it yourself from source.

**Comment by alexanderdean** [comment]
Hey @fubarbaz - here are the packages to install in your Docker image:

* [lzop](https://packages.debian.org/jessie/lzop)
* [liblzo2-dev](https://packages.debian.org/jessie/liblzo2-dev)

**Comment by fubarbaz** [comment]
@alexanderdean Those are Debian packages; I have provided those dependencies via a different method. The problem is the resolution of the libraries associated with those packages and as such I am more interested in how you provide libgplcompression.so.

**Comment by alexanderdean** [comment]
Hi @fubarbaz - it sounds like you are having trouble getting the whole Busybox>JVM>Kinesis S3 to resolve your lzo dependencies? We haven't setup Kinesis S3 on Busybox yet so not sure how much help we will be.

When you get it working it would be awesome if you would open a PR into our WIP Snowplow Docker repo with the solution: https://github.com/snowplow/snowplow-docker/pulls

**Comment by fubarbaz** [comment]
@alexanderdean I found the cause. There is an assumption that `java.io.tmpdir` exists, which wasn't true on my system. It would be nice to remove this assumption or add error handling code for it.

**Comment by alexanderdean** [comment]
Hey @fubarbaz - quoting from the [Java Standard Edition 7 documentation](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getProperties()):

> The current set of system properties for use by the getProperty(String) method is returned as a Properties object. If there is no current set of system properties, a set of system properties is first created and initialized. This set of system properties always includes values for the following keys: 

> java.io.tmpdir 	Default temp file path

So I think your system is not running a full Java 7 SE - please check and fix.

**Comment by fubarbaz** [comment]
@alexanderdean The system property exists. It's just that the file path pointed to, doesn't necessarily exist. The only thing that specification says is that those values exist; not that they have correct values.

**Comment by alexanderdean** [comment]
I admire your persistence @fubarbaz ! If you insist on using a misconfigured runtime environment for Kinesis S3, I suggest you track down our transitive dependency that relies on `java.io.tmpdir` being set to a valid path and petition him or her to not use that file path. Good luck!

**Comment by BenFradet** [comment]
closing :+1:
